### ISSUE TITLE
IKWID doesn't disable the tutorial in the presence of noRecipeBook

### ISSUE THREAD

**Issue by variousauthors** [ChloeDawn/IKnowWhatImDoing#1]
![2020-02-21_23 48 03](https://user-images.githubusercontent.com/541047/75088642-e47f4e80-5504-11ea-92b3-cd17b68071f2.png)

Reproduction Steps

1. in multiMC create a new instance at version 1.12.2
2. install forge and add the following mods:
```
ikwid-1.0.2.jar
noRecipeBook_v1.2.2formc1.12.2.jar
```
3. launch the client, start a new survival world, and wait

After a short period of time, a tutorial begins.

With _just_ ikdwi installed, and not noRecipeBook, there is no tutorial. This is a cross-mod issue, so it might not have anything to do with you, but I feel like these are two mods that should be able to live side-by-side for the betterment of humanity.

**Comment by variousauthors** [comment]
Ha! False alarm, I don't know what I'm doing. The problem was that I created the instance, played a bit, saw the stupid tutorial, installed IKWID, and I guess IKWID doesn't work retroactively? Because, when I followed my reproduction steps (above) I was not able to reproduce on a new instance.

Thanks for the great mod!

**Comment by ChloeDawn** [comment]
This issue is now fixed in [3.2.0](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing/files/3369234). Apologies for not getting to this sooner, I tend to not look at closed tickets as I assume there was no bug. If you encounter something but find a workaround, please do not close the ticket as it does not mean the bug is fixed for everyone else!
